name: Report coverage
run-name: Report coverage
on:
  push:
    branches:
      - main
jobs:
  report-coverage:
    name: Report Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '17'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: 'on-failure'
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Run verification tasks
        id: gradle_run
        run: ./gradlew koverXmlReport

      - name: umami-api - Upload coverage report
        uses: qltysh/qlty-action/coverage@v2.2.0
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: umami-api/build/reports/kover/report.xml
          format: "jacoco"
          skip-errors: false
          add-prefix: umami-api/src/commonMain/kotlin/

      - name: umami - Upload coverage report
        uses: qltysh/qlty-action/coverage@v2.2.0
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: umami/build/reports/kover/report.xml
          format: "jacoco"
          skip-errors: false
          add-prefix: umami/src/commonMain/kotlin/
          validate-file-threshold: 70
